const shell = require('shelljs');
const keygen = require("ssh-keygen-v2");
const os = require('os');
const pathExists = require('path-exists');
const path = require('path');

module.exports = {
    detect: () => true,
    genKey: async (hostname) => {
        location = path.join(os.homedir(), '.ssh');
        if (!pathExists.sync(location)) {
            shell.mkdir("-p", location);
        }
        location = path.join(location, hostname+"_rsa");
        return new Promise((resolve, reject) => {
            keygen(
                {
                  location: location,
                  encryption: 'rsa',
                  size: 4096,
                  comment: "Generated by VSCode SSH Utils",
                },
                function(err, out) {
                  if (err) return reject(err);
                  resolve({
                      public: out.pubKey,
                      private: out.key,
                      location
                  });
                }
              );

        });
    }
}
